### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by bobhenl** [poma123/GlobalWarming#19]
```
[04:07:59] [Server thread/INFO]: [GlobalWarming] Enabling GlobalWarming vDEV - 9 (git d21d264b)
[04:07:59] [Server thread/ERROR]: Error occurred while enabling GlobalWarming vDEV - 9 (git d21d264b) (Is it up to date?)
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
	at me.poma123.globalwarming.items.machines.TemperatureMeter.<init>(TemperatureMeter.java:29) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin$1.<init>(GlobalWarmingPlugin.java:102) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin.registerItems(GlobalWarmingPlugin.java:98) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin.onEnable(GlobalWarmingPlugin.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1048]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
	... 14 more
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.UnregisterReason
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1048]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	... 14 more
[04:07:59] [Server thread/INFO]: [GlobalWarming] Disabling GlobalWarming vDEV - 9 (git d21d264b)
```

**Comment by RIPISDRAD** [comment]
[16:12:45 ERROR]: Error occurred while enabling GlobalWarming vDEV - 9 (git d21d264b) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
        at me.poma123.globalwarming.items.machines.TemperatureMeter.<init>(TemperatureMeter.java:29) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin$1.<init>(GlobalWarmingPlugin.java:102) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin.registerItems(GlobalWarmingPlugin.java:98) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin.onEnable(GlobalWarmingPlugin.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3068/48554357.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.UnregisterReason
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-416]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        ... 15 more
        same problem plz fix and answer

**Comment by Boomer-1** [comment]
rip, loading duplicate error reports isn't necessary.

**Comment by mrcoffee1026** [comment]
confirmed issue, build #9 & sf build 912

**Comment by AgileGhost** [comment]
I got this error on my server, it turns out I forgot the dependency CS-CoreLib Dev#92. After adding this dependency I no longer got this error. Perhaps it may be the same thing.
