### ISSUE TITLE
Can't enabling GlobalWarming

### ISSUE THREAD

**Issue by Ironnoob73** [poma123/GlobalWarming#32]
## Description (REQUIRED)
Server can't enabling this plugin.

## Steps to reproduce the Issue (REQUIRED)
![屏幕截图 2022-02-09 100206.png](https://s2.loli.net/2022/02/09/5krtZlojpRUVv28.png)
![屏幕截图 2022-02-09 095919.png](https://s2.loli.net/2022/02/09/ZNawKBO1Lk5TWf6.png)
![屏幕截图 2022-02-09 095943.png](https://s2.loli.net/2022/02/09/WSqtReP7UMNaOQC.png)

## Expected behavior (REQUIRED)
This plugin should be install currectly.

## Server Log
```
[21:49:18 INFO]: [GlobalWarming] Enabling GlobalWarming vDEV - 11 (git 73ff77d4)
[21:49:18 ERROR]: Error occurred while enabling GlobalWarming vDEV - 11 (git 73ff77d4) (Is it up to date?)
java.lang.NoSuchMethodError: 'io.github.thebusybiscuit.slimefun4.utils.biomes.BiomeMap io.github.thebusybiscuit.slimefun4.utils.biomes.BiomeMap.fromJson(org.bukkit.NamespacedKey, java.lang.String, io.github.thebusybiscuit.slimefun4.utils.biomes.BiomeDataConverter, boolean)'
        at me.poma123.globalwarming.Registry.loadBiomeMap(Registry.java:198) ~[[SlimeFunPluging]GlobalWarming - DEV 11 (git 73ff7).jar:?]
        at me.poma123.globalwarming.Registry.load(Registry.java:62) ~[[SlimeFunPluging]GlobalWarming - DEV 11 (git 73ff7).jar:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin.onEnable(GlobalWarmingPlugin.java:97) ~[[SlimeFunPluging]GlobalWarming - DEV 11 (git 73ff7).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[21:49:18 INFO]: [GlobalWarming] Disabling GlobalWarming vDEV - 11 (git 73ff77d4)
```

## Environment (REQUIRED)
 - Server Software (Spigot/Paper):paper (git-Paper-187)
 - Minecraft Version:1.18.1(server) 1.17.1(client)
 - Slimefun Version:RC - 30 (git fd4b462f)

**Comment by poma123** [comment]
You're using an RC build of Slimefun, but the minimum Slimefun version for GlobalWarming build 11 is Slimefun DEV-996 as on the build page. (The "stable" RC version is older than this DEV version and lacks a needed method for GW to work.)
![Screenshot_20220209-201432_Chrome.jpg](https://user-images.githubusercontent.com/25465545/153273426-03d2eff3-ec41-4d0a-99cd-26243d258dcf.jpg)
